-- s007_metric_analysis_domains.sql
-- Metric-to-domain assignments (132 rows). Universal, all platforms.
-- Drives which metrics are checked by which domain's outlier detection
-- and which v_runs_clean_* views filter on which columns.
-- Source of truth: GN100 live DB, 2026-07-05.
-- See SPEC_SEED_DATA_COMPLETE.md for classification rules.

INSERT OR IGNORE INTO metric_analysis_domains (metric_name, domain_name) VALUES
-- coverage (5 metrics)
('energy_sample_coverage_pct',   'coverage'),
('phase_sample_coverage_pct',    'coverage'),
('spbm_sample_coverage_pct',     'coverage'),
('spbm_samples_expected',        'coverage'),
('spbm_samples_observed',        'coverage'),

-- cpu_perf (18 metrics)
('cache_miss_rate',              'cpu_perf'),
('cache_misses',                 'cpu_perf'),
('cache_references',             'cpu_perf'),
('cpu_avg_mhz',                  'cpu_perf'),
('cpu_busy_mhz',                 'cpu_perf'),
('cycles',                       'cpu_perf'),
('energy_per_cycle',             'cpu_perf'),
('energy_per_instruction',       'cpu_perf'),
('frequency_mhz',                'cpu_perf'),
('instructions',                 'cpu_perf'),
('instructions_per_token',       'cpu_perf'),
('ipc',                          'cpu_perf'),
('l1d_cache_misses_total',       'cpu_perf'),
('l2_cache_misses_total',        'cpu_perf'),
('l3_cache_hits_total',          'cpu_perf'),
('l3_cache_misses_total',        'cpu_perf'),
('ring_bus_freq_mhz',            'cpu_perf'),
('voltage_vcore_avg',            'cpu_perf'),

-- energy (34 metrics)
('attributed_energy_uj',         'energy'),
('avg_power_watts',              'energy'),
('avg_task_power_watts',         'energy'),
('baseline_energy_uj',           'energy'),
('carbon_g',                     'energy'),
('core_energy_uj',               'energy'),
('dram_energy_uj',               'energy'),
('duration_ns',                  'energy'),
('dynamic_energy_uj',            'energy'),
('energy_per_cycle',             'energy'),
('energy_per_instruction',       'energy'),
('energy_per_token',             'energy'),
('execution_energy_uj',          'energy'),
('framework_overhead_energy_uj', 'energy'),
('framework_overhead_ns',        'energy'),
('inter_phase_energy_uj',        'energy'),
('methane_mg',                   'energy'),
('pkg_energy_uj',                'energy'),
('planning_energy_uj',           'energy'),
('post_task_duration_ns',        'energy'),
('post_task_energy_uj',          'energy'),
('pre_task_duration_ns',         'energy'),
('pre_task_energy_uj',           'energy'),
('rapl_after_task_uj',           'energy'),
('rapl_before_pretask_uj',       'energy'),
('spbm_conversion_efficiency',   'energy'),
('spbm_conversion_loss_uj',      'energy'),
('spbm_power_sampling_freq_hz',  'energy'),
('synthesis_energy_uj',          'energy'),
('task_duration_ns',             'energy'),
('total_energy_uj',              'energy'),
('total_run_duration_ns',        'energy'),
('uncore_energy_uj',             'energy'),
('water_ml',                     'energy'),

-- gpu_energy (9 metrics)
('gpu_baseline_energy_uj',       'gpu_energy'),
('gpu_count',                    'gpu_energy'),
('gpu_dynamic_energy_uj',        'gpu_energy'),
('gpu_idle_power_w_used',        'gpu_energy'),
('gpu_pct_of_pkg',               'gpu_energy'),
('gpu_residual_dynamic_uj',      'gpu_energy'),
('gpu_spbm_dynamic_uj',          'gpu_energy'),
('gpu_spbm_total_uj',            'gpu_energy'),
('gpu_total_energy_uj',          'gpu_energy'),

-- llm_perf (8 metrics)
('api_latency_ms',               'llm_perf'),
('completion_tokens',            'llm_perf'),
('instructions_per_token',       'llm_perf'),
('llm_calls',                    'llm_perf'),
('prompt_tokens',                'llm_perf'),
('total_tokens',                 'llm_perf'),
('tpot_ms',                      'llm_perf'),
('ttft_ms',                      'llm_perf'),

-- orchestration (4 metrics)
('orchestration_cpu_ms',         'orchestration'),
('steps',                        'orchestration'),
('tool_calls',                   'orchestration'),
('tools_used',                   'orchestration'),

-- system (33 metrics)
('background_cpu_percent',       'system'),
('bytes_recv',                   'system'),
('bytes_sent',                   'system'),
('c2_time_seconds',              'system'),
('c3_time_seconds',              'system'),
('c6_time_seconds',              'system'),
('c7_time_seconds',              'system'),
('context_switches_involuntary', 'system'),
('context_switches_voluntary',   'system'),
('cpu_fraction',                 'system'),
('disk_read_bytes_total',        'system'),
('disk_write_bytes_total',       'system'),
('dns_latency_ms',               'system'),
('interrupt_rate',               'system'),
('interrupts_per_second',        'system'),
('major_page_faults',            'system'),
('minor_page_faults',            'system'),
('page_faults',                  'system'),
('process_count',                'system'),
('rss_memory_mb',                'system'),
('run_queue_length',             'system'),
('swap_end_cached_mb',           'system'),
('swap_end_free_mb',             'system'),
('swap_end_percent',             'system'),
('swap_end_used_mb',             'system'),
('swap_start_cached_mb',         'system'),
('swap_start_used_mb',           'system'),
('swap_total_mb',                'system'),
('tcp_retransmits',              'system'),
('thread_migrations',            'system'),
('total_context_switches',       'system'),
('vms_memory_mb',                'system'),
('wakeup_latency_us',            'system'),

-- thermal (10 metrics)
('baseline_temp_celsius',        'thermal'),
('max_temp_c',                   'thermal'),
('min_temp_c',                   'thermal'),
('package_temp_celsius',         'thermal'),
('start_temp_c',                 'thermal'),
('thermal_delta_c',              'thermal'),
('thermal_during_experiment',    'thermal'),
('thermal_now_active',           'thermal'),
('thermal_since_boot',           'thermal'),
('thermal_throttle_flag',        'thermal'),

-- timing (11 metrics)
('avg_step_time_ms',             'timing'),
('compute_time_ms',              'timing'),
('duration_ns',                  'timing'),
('execution_time_ms',            'timing'),
('kernel_time_ms',               'timing'),
('phase_execution_ratio',        'timing'),
('phase_planning_ratio',         'timing'),
('phase_synthesis_ratio',        'timing'),
('planning_time_ms',             'timing'),
('synthesis_time_ms',            'timing'),
('user_time_ms',                 'timing');
