#!/usr/bin/env python3
"""
================================================================================
SENSOR READER - Temperature and Voltage Sensors from Sysfs
================================================================================

This module reads temperature and voltage sensors from the Linux sysfs interface.
Unlike turbostat which reads CPU-internal sensors, this reads motherboard and
package sensors exposed by kernel drivers.

Requirements implemented in this module:
- Req 1.9: Package thermal jitter (temperature monitoring)
- Req 1.2: Motherboard voltages (voltage monitoring)
- Req 1.38: System Agent voltage (VSA monitoring)

Sources:
- CPU package temperature: /sys/class/thermal/thermal_zone*/temp
- Core temperatures: Multiple thermal zones
- Voltages: /sys/class/hwmon/hwmon*/in*_input (if available)

Why this matters for AI energy research:
- Thermal throttling detection (Req 1.9)
- Correlation between temperature and energy consumption
- Validation that cooling is sufficient between runs

Author: Deepak Panigrahy
================================================================================
"""

import glob
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ============================================================================
# FIX PYTHON PATH
# ============================================================================
project_root = Path(__file__).parent.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from core.models.energy_measurement import ThermalReadings
from core.utils.debug import dprint

logger = logging.getLogger(__name__)


class SensorReader:
    """
    Reads temperature and voltage sensors from sysfs.

    This class implements:
    - Req 1.9: Package thermal jitter (temperature monitoring)
    - Req 1.2: Motherboard voltages (voltage monitoring)
    - Req 1.38: System Agent voltage (VSA monitoring)
    from core.utils.debug import dprint
    All paths are read from hw_config.json, which is generated by
    detect_hardware.py during system detection.
    """

    def __init__(self, config: Dict):
        """
        Initialize sensor reader with configuration from Module 0.

        Args:
            config: Hardware configuration from hw_config.json.
                   Must contain 'thermal' section with paths.

        Example config:
            "thermal": {
                "paths": {
                    "x86_pkg_temp": "/sys/class/thermal/thermal_zone7/temp",
                    "SEN1": "/sys/class/thermal/thermal_zone0/temp",
                    ...
                },
                "package_temp": "x86_pkg_temp"
            }
        """
        self.thermal_config = config.get("thermal", {})
        self.thermal_paths = self.thermal_config.get("paths", {})
        self.package_temp_key = self.thermal_config.get("package_temp")

        # Store config for later initialization
        self.sensors_to_monitor = self.thermal_config.get("sensors_to_monitor", {})

        # Don't open files yet - wait for initialize()
        self.thermal_fds = {}
        self.throttle_thresholds = {}
        self.discovered_zones = {}
        self._initialized = False

        # Validate available sensors (only paths, not file handles)
        self.available_sensors = self._validate_paths()

        logger.info(
            f"SensorReader created with {len(self.available_sensors)} sensors (not initialized)"
        )

    def initialize(self):
        """Initialize thermal sampling - call after config is fully loaded"""
        if self._initialized:
            return

        # Discover thermal zones at runtime
        self.discovered_zones = self._discover_thermal_zones()

        # Open file handles for configured sensors
        for role, sensor_type in self.sensors_to_monitor.items():
            sensor_infos = self.discovered_zones.get(sensor_type, [])
            if sensor_infos:
                path = sensor_infos[0]["path"]
                try:
                    self.thermal_fds[role] = open(path, "r")
                    if sensor_infos[0].get("throttle_temp"):
                        self.throttle_thresholds[role] = sensor_infos[0][
                            "throttle_temp"
                        ]
                    logger.debug(f"Opened thermal sensor {role} -> {path}")
                except Exception as e:
                    logger.warning(f"Could not open thermal sensor {role}: {e}")

        self._initialized = True
        logger.info(
            f"SensorReader initialized with {len(self.thermal_fds)} thermal sensors"
        )

    def close(self):
        """Close all open thermal file handles."""
        for fd in self.thermal_fds.values():
            try:
                fd.close()
            except:
                pass

    def _discover_thermal_zones(self):
        """Discover thermal zones at runtime (handles reboots)"""
        base = "/sys/class/thermal"
        mapping = {}

        for entry in os.listdir(base):
            if entry.startswith("thermal_zone"):
                zone_path = os.path.join(base, entry)
                try:
                    with open(os.path.join(zone_path, "type")) as f:
                        sensor_type = f.read().strip()
                    temp_file = os.path.join(zone_path, "temp")
                    trip_point = os.path.join(zone_path, "trip_point_0_temp")

                    throttle_temp = None
                    if os.path.exists(trip_point):
                        with open(trip_point) as f:
                            throttle_temp = int(f.read().strip()) / 1000.0

                    if os.path.exists(temp_file):
                        mapping.setdefault(sensor_type, []).append(
                            {
                                "path": temp_file,
                                "zone": entry,
                                "throttle_temp": throttle_temp,
                            }
                        )
                except Exception:
                    continue
        return mapping

    def read_all_thermal(self) -> Dict[str, Optional[float]]:
        """
        Read all configured thermal sensors.

        Returns:
            Dictionary mapping role -> temperature in °C (or None if failed)
        """
        # Initialize with all expected roles
        readings = {role: None for role in self.sensors_to_monitor.keys()}

        for role, fd in self.thermal_fds.items():
            try:
                fd.seek(0)
                temp_raw = int(fd.readline().strip())
                readings[role] = temp_raw / 1000.0
            except Exception as e:
                logger.debug(f"Failed to read thermal sensor {role}: {e}")
                # readings[role] already None from initialization

        # Debug print to verify readings
        dprint(f"🔍 THERMAL READINGS: {readings}")

        return readings

    def _validate_paths(self) -> Dict[str, str]:
        """
        Validate which sensor paths are actually accessible.

        Returns:
            Dictionary of sensor name -> path for accessible sensors
        """
        available = {}
        for name, path in self.thermal_paths.items():
            if os.path.exists(path):
                try:
                    # Test read (just a few bytes)
                    with open(path, "r") as f:
                        f.read(10)
                    available[name] = path
                    logger.debug(f"Sensor available: {name} at {path}")
                except (IOError, PermissionError) as e:
                    logger.warning(f"Sensor {name} not readable: {e}")
            else:
                logger.debug(f"Sensor path not found: {path}")

        return available

    def read_temperatures(self) -> ThermalReadings:
        """
        Read all temperature sensors and return ThermalReadings object.

        Req 1.9: Package thermal jitter - Reads CPU package temperature
        to detect thermal throttling and ensure measurement validity.

        Returns:
            ThermalReadings object containing:
            - package_temperature_celsius
            - core_temperatures_celsius (list)
            - Any other available thermal data
        """
        thermal = ThermalReadings()
        core_temps = []

        for name, path in self.available_sensors.items():
            try:
                with open(path, "r") as f:
                    raw_value = f.read().strip()

                # Convert to Celsius (sensors report millidegrees)
                temp_celsius = int(raw_value) / 1000.0

                # Req 1.9: Capture package temperature for thermal analysis
                if name == self.package_temp_key:
                    thermal.package_temperature_celsius = temp_celsius
                    logger.debug(f"Package temp: {temp_celsius:.1f}°C")

                    # Req 1.9: Detect thermal throttling threshold
                    if temp_celsius > 85:
                        thermal.thermal_throttle_count += 1
                        logger.warning(
                            f"High temperature detected: {temp_celsius:.1f}°C"
                        )

                # Req 1.9: Also track per-core temperatures for granular analysis
                elif "core" in name.lower() or "sen" in name.lower():
                    core_temps.append(temp_celsius)
                    logger.debug(f"Core temp {name}: {temp_celsius:.1f}°C")
                elif "gpu" in name.lower():
                    thermal.gpu_temperature_celsius = temp_celsius
                elif "pch" in name.lower():
                    thermal.pch_temperature_celsius = temp_celsius

            except Exception as e:
                logger.debug(f"Failed to read sensor {name}: {e}")

        thermal.core_temperatures_celsius = core_temps

        # Req 1.9: Check for thermal throttling (if temperature > 85°C)
        if thermal.package_temperature_celsius > 85:
            thermal.thermal_throttle_count += 1
            logger.warning(
                f"High temperature detected: {thermal.package_temperature_celsius:.1f}°C"
            )

        return thermal

    def read_voltages(self) -> Dict[str, float]:
        """
        Read voltage sensors from hwmon interface (if available).

        Req 1.2: Motherboard voltages - Reads voltage rails to detect
        if the board over-volts during rapid state transitions.

        Req 1.38: System Agent voltage - Specifically looks for VSA
        to detect if SoC keeps interconnect "hot" during idle.

        This is optional and may not be available on all systems.

        Returns:
            Dictionary mapping voltage names to values in volts.
            Example: {'Vcore': 1.2, 'VSA': 1.05}
        """
        voltages = {}

        # Look for hwmon directories
        hwmon_paths = glob.glob("/sys/class/hwmon/hwmon*")

        for hwmon in hwmon_paths:
            name_file = os.path.join(hwmon, "name")
            if not os.path.exists(name_file):
                continue

            try:
                with open(name_file, "r") as f:
                    hwmon_name = f.read().strip()

                # Look for voltage inputs (in0_input, in1_input, etc.)
                for i in range(10):  # Check up to 10 inputs
                    in_path = os.path.join(hwmon, f"in{i}_input")
                    label_path = os.path.join(hwmon, f"in{i}_label")

                    if os.path.exists(in_path):
                        with open(in_path, "r") as f:
                            # Value is in millivolts
                            mv = int(f.read().strip())
                            volts = mv / 1000.0

                        # Req 1.2: Try to get a label for identification
                        if os.path.exists(label_path):
                            with open(label_path, "r") as f:
                                label = f.read().strip()
                            voltages[label] = volts

                            # Req 1.38: Specifically track System Agent voltage
                            if (
                                "VSA" in label
                                or "SA" in label
                                or "System Agent" in label
                            ):
                                logger.debug(f"System Agent voltage: {volts:.3f}V")
                        else:
                            voltages[f"{hwmon_name}_in{i}"] = volts

                        logger.debug(f"Voltage {i}: {volts:.3f}V")

            except Exception as e:
                logger.debug(f"Error reading hwmon {hwmon}: {e}")

        return voltages

    def read_throttle_events(self) -> int:
        """
        Read thermal throttle events from MSR or sysfs.

        Req 1.9: Thermal throttling events - Counts how many times
        the CPU has throttled due to high temperature.

        This is a simplified version – full throttle detection
        requires MSR access which is handled by msr_reader.py.

        Returns:
            Number of throttle events (0 if not available)
        """
        # Check if there's a throttle counter in thermal zone
        for name, path in self.available_sensors.items():
            if "throttle" in name.lower():
                try:
                    with open(path, "r") as f:
                        return int(f.read().strip())
                except:
                    pass

        return 0

    def is_throttling(self, threshold: float = 85.0) -> bool:
        """
        Quick check if CPU is thermal throttling.

        Req 1.9: Thermal throttling detection - If temperature exceeds
        threshold, measurements may be unreliable due to frequency reduction.

        Args:
            threshold: Temperature threshold in Celsius (default 85°C)

        Returns:
            True if package temperature exceeds threshold
        """
        # Read current temperatures
        thermal = self.read_temperatures()

        # Req 1.9: Check against threshold
        is_throttling = thermal.package_temperature_celsius > threshold

        if is_throttling:
            logger.warning(
                f"Thermal throttling detected: {thermal.package_temperature_celsius:.1f}°C > {threshold}°C"
            )

        return is_throttling

# --- ThermalReaderABC compatibility (Chunk 1) ---
    def get_name(self) -> str:
        """Return reader name for factory logging."""
        return "SensorReader"

    def is_available(self) -> bool:
        """Return True if any thermal sensors are accessible."""
        return len(self.available_sensors) > 0
    
    def __str__(self) -> str:
        """String representation."""
        return f"SensorReader(sensors={len(self.available_sensors)})"


# ============================================================================
# USAGE EXAMPLE
# ============================================================================

if __name__ == "__main__":
    import json
    import time

    # Set up logging
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    print("\n" + "=" * 70)
    print("SENSOR READER TEST")
    print("=" * 70)

    # Load config
    config_path = Path("config/hw_config.json")
    if not config_path.exists():
        print("❌ Config file not found!")
        sys.exit(1)

    with open(config_path) as f:
        config = json.load(f)
    print(f"✅ Loaded config from {config_path}")

    # Initialize reader
    reader = SensorReader(config)
    print(f"📊 {reader}")

    # Read temperatures
    print("\n📝 Reading temperatures...")
    thermal = reader.read_temperatures()

    print("\n" + "=" * 70)
    print("TEMPERATURES (Req 1.9)")
    print("=" * 70)
    print(f"   Package: {thermal.package_temperature_celsius:.1f}°C")
    if thermal.core_temperatures_celsius:
        print(
            f"   Cores: {', '.join([f'{t:.1f}°C' for t in thermal.core_temperatures_celsius])}"
        )
    if thermal.gpu_temperature_celsius > 0:
        print(f"   GPU: {thermal.gpu_temperature_celsius:.1f}°C")
    if thermal.pch_temperature_celsius > 0:
        print(f"   PCH: {thermal.pch_temperature_celsius:.1f}°C")

    # Check throttling (Req 1.9)
    if reader.is_throttling():
        print("\n⚠️  CPU is thermal throttling!")
    else:
        print("\n✅ CPU temperature normal")

    # Try to read voltages (Req 1.2, 1.38)
    print("\n" + "=" * 70)
    print("VOLTAGES (Req 1.2, 1.38) - if available")
    print("=" * 70)
    voltages = reader.read_voltages()
    if voltages:
        for name, volts in voltages.items():
            print(f"   {name}: {volts:.3f}V")
    else:
        print("   No voltage sensors available")

    print("\n" + "=" * 70)
    print("✅ Test complete!")
    print("=" * 70)
