-- =============================================================================
-- Migration v80: Purpose-Conditional Outlier Validity (DDL only)
-- =============================================================================
-- Schema version target: 80
-- Prerequisite: migration v79 (schema 79) live on GN100
--
-- Additive only. Does not modify run_outliers row data, v_runs_clean
-- (the v1 blanket view), or any pre-existing table.
--
-- Three-tier view model (decided after v1 review surfaced the CPU
-- frequency case and the worst-case-energy-run case):
--   v_runs_clean_<domain>    excludes BOTH outlier_class values
--   v_runs_measured_<domain> excludes only data_quality_failure,
--                            keeps statistical_anomaly (real but unusual)
--   v_runs_unfiltered        already exists from v79, unchanged
--
-- MSC-4 compliance: this file is DDL only. Seed data lives in
-- v80_outlier_v2_seed.sql. Domain-scoped view CREATE statements are
-- generated by v80_outlier_v2_views.py after seed data loads, since the
-- view SQL depends on querying analysis_view_config and
-- analysis_domain_config at generation time, not on hardcoded text.
--
-- Forward only. Do NOT apply to frozen Paper 1 snapshot databases.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- analysis_domain_config
-- The ten analysis domains (nine real + identity, which is never
-- outlier-detected). coverage is the sole foundation domain.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analysis_domain_config (
    domain_name         TEXT PRIMARY KEY,
    is_foundation        INTEGER NOT NULL DEFAULT 0,
    description            TEXT NOT NULL,
    column_count             INTEGER NOT NULL,
    created_at                  TIMESTAMP NOT NULL
        DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- -----------------------------------------------------------------------------
-- metric_analysis_domains
-- Many-to-many: which domain(s) each runs.* column belongs to. A handful
-- of columns (energy_per_cycle, duration_ns, etc) legitimately belong to
-- two domains, hence many-to-many rather than a single domain_name column
-- on the metric itself.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS metric_analysis_domains (
    metric_name          TEXT NOT NULL,
    domain_name            TEXT NOT NULL,
    rationale                 TEXT,

    PRIMARY KEY (metric_name, domain_name),
    FOREIGN KEY (domain_name) REFERENCES analysis_domain_config(domain_name)
);

CREATE INDEX IF NOT EXISTS idx_mad_domain ON metric_analysis_domains(domain_name);

-- -----------------------------------------------------------------------------
-- analysis_view_config
-- Which domain(s) each purpose-scoped view depends on, plus whether that
-- view propagates foundation-domain (coverage) exclusions. include_foundation
-- is per (view_name, domain_name) row in storage, but is set to the same
-- value across all rows of one view_name by convention (see 6.3 of
-- SPEC_OUTLIER_V2.md), enforced by application logic, not a DB constraint.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analysis_view_config (
    view_name             TEXT NOT NULL,
    domain_name             TEXT NOT NULL,
    include_foundation         INTEGER NOT NULL DEFAULT 1,

    PRIMARY KEY (view_name, domain_name),
    FOREIGN KEY (domain_name) REFERENCES analysis_domain_config(domain_name)
);

-- -----------------------------------------------------------------------------
-- run_outliers gets outlier_class (Rule SC-2: ALTER TABLE migration must
-- have a matching schema.py change, tracked separately in the deployment
-- manifest for this migration)
-- -----------------------------------------------------------------------------
ALTER TABLE run_outliers ADD COLUMN outlier_class TEXT
    DEFAULT 'data_quality_failure';

-- -----------------------------------------------------------------------------
-- outlier_detection_config gets outlier_class, making classification
-- config-driven rather than hardcoded in compute_outliers.py
-- -----------------------------------------------------------------------------
ALTER TABLE outlier_detection_config ADD COLUMN outlier_class TEXT
    DEFAULT 'data_quality_failure';

-- -----------------------------------------------------------------------------
-- schema_version bump (Rule SC-7)
-- -----------------------------------------------------------------------------
INSERT INTO schema_version (version, applied_at, description)
VALUES (
    80,
    datetime('now'),
    'Purpose-conditional outlier validity: analysis_domain_config, metric_analysis_domains, analysis_view_config, run_outliers.outlier_class, outlier_detection_config.outlier_class. Three-tier view model: v_runs_clean_<domain> (excludes both outlier classes), v_runs_measured_<domain> (excludes only data_quality_failure). 14 total views after v80_outlier_v2_views.py runs (6 clean + 6 measured + existing v_runs_clean + v_runs_unfiltered from migration v79).'
);
