#!/usr/bin/env python3
"""
================================================================================
DATABASE MANAGER – Module 4: Persistent Storage for A‑LEMS Experiments
================================================================================

PURPOSE:
    This module provides a complete SQLite database interface for storing
    all experiment data generated by the A‑LEMS system. It implements the
    final 10‑table schema designed for research‑grade analysis, including
    runs, orchestration events, high‑frequency samples, tax summaries,
    and a flattened ML view.

WHY IT EXISTS:
    - To enable long‑term storage and reproducibility of all measurements.
    - To support GUI queries (fast, indexed) for interactive exploration.
    - To provide a single flat table (ml_features) for machine learning training.
    - To preserve all raw and derived data for future analysis without
      having to re‑run experiments.

UNITS AND SCIENTIFIC ASSUMPTIONS:
    - All times are stored in nanoseconds (ns) for integer precision.
    - All energies are stored in microjoules (µJ) to avoid floating‑point drift.
    - Power is stored in watts (J/s) as REAL.
    - Frequencies in MHz (megahertz), temperatures in °C.
    - Baseline correction: dynamic_energy = total_energy - idle_baseline_energy.
    - Orchestration tax = agentic_dynamic - linear_dynamic (paired runs).
    - Tax is distributed proportionally to each event's energy.
    - All derived columns (energy_per_instruction, etc.) are computed in Python
      to ensure correctness and are stored for ML convenience.
    - We assume that linear and agentic runs are paired by `run_number` within
      the same experiment.

WHAT IT MUST NEVER BREAK:
    - Must never lose data: all inserts are transactional.
    - Must never corrupt foreign key relationships.
    - Must never insert duplicate runs (enforced by unique index).
    - Must never miscalculate tax due to missing pairs.

AUTHOR: Deepak Panigrahy
================================================================================
"""

import hashlib
import json
import logging
import os
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ------------------------------------------------------------------------------
# SCHEMA DEFINITIONS (SQL)
# ------------------------------------------------------------------------------
# All CREATE TABLE statements are kept here for clarity and version control.
# Each table is documented with its purpose and column units.

CREATE_EXPERIMENTS = """
-- experiments: top‑level metadata for each experiment run.
-- Columns:
--   exp_id            : auto‑increment primary key
--   name              : human‑readable experiment name
--   description       : free‑text description
--   workflow_type     : 'linear' or 'agentic' – defines the execution mode
--   model_name        : LLM model identifier (e.g., 'llama-3.3-70b-versatile')
--   provider          : API provider (e.g., 'groq', 'ollama')
--   task_name         : task identifier (e.g., 'capital', 'explain')
--   country_code      : ISO country code for grid carbon intensity
--   created_at        : timestamp when experiment record was created
CREATE TABLE IF NOT EXISTS experiments (
    exp_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    workflow_type TEXT CHECK(workflow_type IN ('linear','agentic')),
    model_name TEXT,
    provider TEXT,
    task_name TEXT,
    country_code TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_HARDWARE_CONFIG = """
-- hardware_config: fixed hardware characteristics of the machine.
-- This table is populated once per machine and reused across runs.
-- Columns:
--   hw_id             : auto‑increment primary key
--   hostname          : machine hostname (for identification)
--   cpu_model         : CPU model string (from /proc/cpuinfo)
--   cpu_cores         : number of physical cores
--   cpu_threads       : number of logical threads (including hyper‑threading)
--   ram_gb            : total RAM in gigabytes (approx)
--   kernel_version    : kernel release (uname -r)
--   microcode_version : CPU microcode version (from /proc/cpuinfo)
--   rapl_domains      : comma‑separated list of available RAPL domains
--   created_at        : timestamp when this record was created
CREATE TABLE IF NOT EXISTS hardware_config (
    hw_id INTEGER PRIMARY KEY AUTOINCREMENT,
    hostname TEXT,
    cpu_model TEXT,
    cpu_cores INTEGER,
    cpu_threads INTEGER,
    ram_gb INTEGER,
    kernel_version TEXT,
    microcode_version TEXT,
    rapl_domains TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_IDLE_BASELINES = """
-- idle_baselines: idle power measurements used for baseline correction.
-- Columns:
--   baseline_id        : unique identifier (e.g., 'baseline_1740595200')
--   timestamp          : Unix timestamp (seconds) when baseline was taken
--   package_power_watts: average idle power of the whole package
--   core_power_watts   : average idle power of cores
--   uncore_power_watts : average idle power of uncore (if available)
--   dram_power_watts   : average idle power of DRAM (if available)
--   duration_seconds   : total duration of baseline measurement
--   sample_count       : number of samples taken
--   package_std        : standard deviation of package power (shows stability)
--   core_std           : standard deviation of core power
--   uncore_std         : standard deviation of uncore power
--   dram_std           : standard deviation of DRAM power
--   governor           : CPU governor active during baseline ('performance','powersave')
--   turbo              : 'enabled' or 'disabled' – turbo boost state
--   background_cpu     : average background CPU % during baseline
--   process_count      : number of running processes during baseline
--   method             : how baseline was obtained (e.g., 'fresh_measurement')
CREATE TABLE IF NOT EXISTS idle_baselines (
    baseline_id TEXT PRIMARY KEY,
    timestamp REAL NOT NULL,
    package_power_watts REAL,
    core_power_watts REAL,
    uncore_power_watts REAL,
    dram_power_watts REAL,
    duration_seconds INTEGER,
    sample_count INTEGER,
    package_std REAL,
    core_std REAL,
    uncore_std REAL,
    dram_std REAL,
    governor TEXT,
    turbo TEXT,
    background_cpu REAL,
    process_count INTEGER,
    method TEXT
);
"""

CREATE_RUNS = """
-- runs: core table containing all per‑run aggregated metrics.
-- This is the central table; every other table references it via run_id.
-- Columns are grouped by category for readability.
-- Units are documented in comments after each group.
CREATE TABLE IF NOT EXISTS runs (
    run_id INTEGER PRIMARY KEY AUTOINCREMENT,
    exp_id INTEGER NOT NULL,
    hw_id INTEGER,
    baseline_id TEXT,
    run_number INTEGER,                     -- run index within experiment

    -- Timing (all in nanoseconds)
    start_time_ns INTEGER,
    end_time_ns INTEGER,
    duration_ns INTEGER,

    -- Energy (all in microjoules; convert to Joules by dividing by 1e6)
    total_energy_uj INTEGER,                 -- raw total energy from RAPL
    dynamic_energy_uj INTEGER,                -- total minus baseline energy
    baseline_energy_uj INTEGER,                -- idle energy during same period
    avg_power_watts REAL,                      -- total_energy_j / duration_seconds

    -- Performance counters
    instructions BIGINT,
    cycles BIGINT,
    ipc REAL,                                  -- instructions per cycle
    cache_misses BIGINT,
    cache_references BIGINT,
    cache_miss_rate REAL,                      -- cache_misses / cache_references
    page_faults INTEGER,
    major_page_faults INTEGER,
    minor_page_faults INTEGER,

    -- Scheduler metrics
    context_switches_voluntary INTEGER,
    context_switches_involuntary INTEGER,
    total_context_switches INTEGER,
    thread_migrations INTEGER,
    run_queue_length REAL,                      -- average number of processes waiting
    kernel_time_ms REAL,                         -- time spent in kernel (ms)
    user_time_ms REAL,                           -- time spent in user space (ms)

    -- Frequency & ring bus
    frequency_mhz REAL,                          -- average CPU frequency
    ring_bus_freq_mhz REAL,                      -- ring bus frequency

    -- Thermal metrics
    package_temp_celsius REAL,                    -- average package temperature
    baseline_temp_celsius REAL,                    -- idle temperature from baseline
    start_temp_c REAL,                             -- temperature at start of run
    max_temp_c REAL,                               -- peak temperature during run
    thermal_delta_c REAL,                          -- max_temp - start_temp (heating)
    thermal_during_experiment BOOLEAN,              -- whether thermal throttling occurred during run
    thermal_now_active BOOLEAN,                     -- whether throttling active at end
    thermal_since_boot BOOLEAN,                     -- whether throttling occurred since boot
    experiment_valid BOOLEAN,                       -- true if no throttling during run and at end

    -- C‑state residencies (seconds spent in each state, since boot, but we take delta)
    c2_time_seconds REAL,
    c3_time_seconds REAL,
    c6_time_seconds REAL,
    c7_time_seconds REAL,

    -- MSR / wakeup
    wakeup_latency_us REAL,                         -- average wakeup latency (microseconds)
    interrupt_rate REAL,                             -- interrupts per second during run
    thermal_throttle_flag INTEGER,                   -- raw throttle count from MSR

    -- Memory usage (process level)
    rss_memory_mb REAL,                              -- Resident Set Size (MB)
    vms_memory_mb REAL,                              -- Virtual Memory Size (MB)

    -- Token counts (for LLM calls)
    total_tokens INTEGER,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,

    -- Network latencies (milliseconds)
    dns_latency_ms REAL,
    api_latency_ms REAL,
    compute_time_ms REAL,

    -- System state at run time
    governor TEXT,
    turbo_enabled BOOLEAN,
    is_cold_start BOOLEAN,
    background_cpu_percent REAL,
    process_count INTEGER,

    -- Agentic‑specific metrics (NULL for linear runs)
    planning_time_ms REAL,
    execution_time_ms REAL,
    synthesis_time_ms REAL,
    phase_planning_ratio REAL,
    phase_execution_ratio REAL,
    phase_synthesis_ratio REAL,
    llm_calls INTEGER,
    tool_calls INTEGER,
    tools_used INTEGER,
    steps INTEGER,
    avg_step_time_ms REAL,
    complexity_level INTEGER,
    complexity_score REAL,

    -- Sustainability metrics (from Module 2)
    carbon_g REAL,                                   -- grams CO₂ equivalent
    water_ml REAL,                                   -- milliliters of water
    methane_mg REAL,                                 -- milligrams of methane

    -- Derived efficiency metrics (computed in Python, stored for ML convenience)
    energy_per_instruction REAL,                      -- Joules per instruction
    energy_per_cycle REAL,                            -- Joules per cycle
    energy_per_token REAL,                            -- Joules per token
    instructions_per_token REAL,
    interrupts_per_second REAL,                       -- same as interrupt_rate

    -- Cryptographic run state hash (for reproducibility)
    run_state_hash TEXT,

    FOREIGN KEY(exp_id) REFERENCES experiments(exp_id),
    FOREIGN KEY(hw_id) REFERENCES hardware_config(hw_id),
    FOREIGN KEY(baseline_id) REFERENCES idle_baselines(baseline_id)
);
"""

CREATE_RUNS_INDEXES = """
-- Indexes for runs table: speed up common queries.
CREATE INDEX IF NOT EXISTS idx_runs_exp_id ON runs(exp_id);
CREATE INDEX IF NOT EXISTS idx_runs_hw_id ON runs(hw_id);
CREATE INDEX IF NOT EXISTS idx_runs_energy ON runs(total_energy_uj);
CREATE INDEX IF NOT EXISTS idx_runs_ipc ON runs(ipc);
CREATE INDEX IF NOT EXISTS idx_runs_interrupt ON runs(interrupt_rate);
CREATE UNIQUE INDEX IF NOT EXISTS idx_runs_unique ON runs(exp_id, run_number);
"""

CREATE_ORCHESTRATION_EVENTS = """
-- orchestration_events: phase‑ and event‑level attribution.
-- Each row represents a single atomic event during an agentic run
-- (e.g., an LLM call, a tool execution, a waiting period).
-- This enables fine‑grained analysis of where energy and tax are spent.
CREATE TABLE IF NOT EXISTS orchestration_events (
    event_id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id INTEGER NOT NULL,
    step_index INTEGER,                         -- step number within the agentic flow
    phase TEXT CHECK(phase IN ('planning','execution','waiting','synthesis')),
    event_type TEXT NOT NULL,                    -- e.g., 'llm_call', 'tool_call', 'network_wait'
    start_time_ns INTEGER NOT NULL,
    end_time_ns INTEGER NOT NULL,
    duration_ns INTEGER NOT NULL,
    power_watts REAL,                             -- average power during event
    cpu_util_percent REAL,
    interrupt_rate REAL,                          -- average interrupt rate during event
    event_energy_uj INTEGER,                       -- energy attributed to this event
    tax_contribution_uj INTEGER,                    -- portion of total tax attributed to this event
    tax_percent REAL,                               -- (tax_contribution / total_tax) * 100
    FOREIGN KEY(run_id) REFERENCES runs(run_id)
);
"""

CREATE_EVENTS_INDEXES = """
CREATE INDEX IF NOT EXISTS idx_events_run ON orchestration_events(run_id);
CREATE INDEX IF NOT EXISTS idx_events_phase ON orchestration_events(phase);
"""

CREATE_TAX_SUMMARY = """
-- orchestration_tax_summary: pre‑computed tax for each linear/agentic pair.
-- This table stores the comparison results for quick GUI display.
CREATE TABLE IF NOT EXISTS orchestration_tax_summary (
    comparison_id INTEGER PRIMARY KEY AUTOINCREMENT,
    linear_run_id INTEGER NOT NULL,
    agentic_run_id INTEGER NOT NULL,
    linear_dynamic_uj INTEGER,                     -- dynamic energy of linear run
    agentic_dynamic_uj INTEGER,                     -- dynamic energy of agentic run
    orchestration_tax_uj INTEGER,                    -- agentic_dynamic - linear_dynamic
    tax_percent REAL,                                -- (tax / agentic_dynamic) * 100
    FOREIGN KEY(linear_run_id) REFERENCES runs(run_id),
    FOREIGN KEY(agentic_run_id) REFERENCES runs(run_id)
);
"""

CREATE_TAX_INDEXES = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_tax_pair ON orchestration_tax_summary(linear_run_id, agentic_run_id);
"""

CREATE_ENERGY_SAMPLES = """
-- energy_samples: high‑frequency RAPL samples (optional).
-- Each row is a snapshot of RAPL counters at a specific time.
-- This allows reconstruction of power traces.
CREATE TABLE IF NOT EXISTS energy_samples (
    sample_id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id INTEGER NOT NULL,
    timestamp_ns INTEGER NOT NULL,
    pkg_energy_uj INTEGER,
    core_energy_uj INTEGER,
    uncore_energy_uj INTEGER,
    dram_energy_uj INTEGER,
    FOREIGN KEY(run_id) REFERENCES runs(run_id)
);
CREATE INDEX IF NOT EXISTS idx_energy_run_time ON energy_samples(run_id, timestamp_ns);
"""

CREATE_CPU_SAMPLES = """
-- cpu_samples: high‑frequency CPU utilization and frequency samples.
CREATE TABLE IF NOT EXISTS cpu_samples (
    sample_id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id INTEGER NOT NULL,
    timestamp_ns INTEGER NOT NULL,
    cpu_util_percent REAL,
    cpu_freq_mhz REAL,
    FOREIGN KEY(run_id) REFERENCES runs(run_id)
);
CREATE INDEX IF NOT EXISTS idx_cpu_run_time ON cpu_samples(run_id, timestamp_ns);
"""

CREATE_INTERRUPT_SAMPLES = """
-- interrupt_samples: high‑frequency interrupt rate samples.
CREATE TABLE IF NOT EXISTS interrupt_samples (
    sample_id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id INTEGER NOT NULL,
    timestamp_ns INTEGER NOT NULL,
    interrupts_per_sec REAL,
    FOREIGN KEY(run_id) REFERENCES runs(run_id)
);
CREATE INDEX IF NOT EXISTS idx_interrupt_run_time ON interrupt_samples(run_id, timestamp_ns);
"""

CREATE_ML_VIEW = """
-- ml_features: flattened view for machine learning.
-- This view denormalizes all relevant columns into a single row per run,
-- making it trivial to load training data without any joins.
-- It also computes the target variables (energy_j, orchestration_tax_j, energy_per_token).
CREATE VIEW IF NOT EXISTS ml_features AS
SELECT
    r.run_id,
    e.workflow_type,
    e.country_code,
    e.model_name,
    e.provider,
    r.run_number,
    r.duration_ns / 1e6 AS duration_ms,
    r.total_energy_uj / 1e6 AS energy_j,
    r.dynamic_energy_uj / 1e6 AS dynamic_energy_j,
    r.avg_power_watts,
    r.instructions,
    r.cycles,
    r.ipc,
    r.cache_misses,
    r.cache_references,
    r.cache_miss_rate,
    r.page_faults,
    r.major_page_faults,
    r.minor_page_faults,
    r.context_switches_voluntary,
    r.context_switches_involuntary,
    r.total_context_switches,
    r.thread_migrations,
    r.run_queue_length,
    r.kernel_time_ms,
    r.user_time_ms,
    r.frequency_mhz,
    r.ring_bus_freq_mhz,
    r.package_temp_celsius,
    r.start_temp_c,
    r.max_temp_c,
    r.thermal_delta_c,
    r.c2_time_seconds,
    r.c3_time_seconds,
    r.c6_time_seconds,
    r.c7_time_seconds,
    r.wakeup_latency_us,
    r.interrupt_rate,
    r.thermal_throttle_flag,
    r.rss_memory_mb,
    r.vms_memory_mb,
    r.total_tokens,
    r.prompt_tokens,
    r.completion_tokens,
    r.dns_latency_ms,
    r.api_latency_ms,
    r.compute_time_ms,
    r.governor,
    r.turbo_enabled,
    r.is_cold_start,
    r.background_cpu_percent,
    r.process_count,
    r.planning_time_ms,
    r.execution_time_ms,
    r.synthesis_time_ms,
    r.phase_planning_ratio,
    r.phase_execution_ratio,
    r.phase_synthesis_ratio,
    r.llm_calls,
    r.tool_calls,
    r.tools_used,
    r.steps,
    r.avg_step_time_ms,
    r.complexity_level,
    r.complexity_score,
    r.carbon_g,
    r.water_ml,
    r.methane_mg,
    r.run_state_hash,
    r.energy_per_instruction,
    r.energy_per_cycle,
    r.energy_per_token,
    r.instructions_per_token,
    r.interrupts_per_second,
    -- Targets (explicitly computed for ML)
    r.total_energy_uj / 1e6 AS energy_j,
    CASE 
        WHEN e.workflow_type = 'agentic' 
        THEN ots.orchestration_tax_uj / 1e6
        ELSE 0
    END AS orchestration_tax_j,
    CASE 
        WHEN r.total_tokens > 0 
        THEN (r.total_energy_uj / 1e6) / r.total_tokens 
        ELSE 0 
    END AS energy_per_token
FROM runs r
JOIN experiments e ON r.exp_id = e.exp_id
LEFT JOIN orchestration_tax_summary ots ON r.run_id = ots.agentic_run_id;
"""

# ------------------------------------------------------------------------------
# DATABASE MANAGER CLASS
# ------------------------------------------------------------------------------


class DatabaseManager:
    """
    Main interface to the A‑LEMS SQLite database.

    This class handles all interactions with the persistent storage:
    - Creating tables and indexes.
    - Inserting experiments, runs, events, samples.
    - Computing tax summaries and run state hashes.
    - Providing query methods for GUI and ML.

    All insert operations are transactional to ensure consistency.
    Units are strictly enforced: times in ns, energies in µJ.
    """

    def __init__(self, db_path: str = "data/experiments.db"):
        """
        Initialize database connection and create tables if they don't exist.

        Args:
            db_path: Path to the SQLite database file.
                    Default is "data/experiments.db" relative to project root.
        """
        # Ensure the directory exists – SQLite won't create intermediate directories.
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)

        self.db_path = db_path
        # Connect and enable foreign key support (critical for data integrity).
        self.conn = sqlite3.connect(db_path)
        self.conn.execute("PRAGMA foreign_keys = ON")
        # Use Row factory so we can access columns by name.
        self.conn.row_factory = sqlite3.Row

        # Create all tables and indexes.
        self._create_tables()

        logger.info(f"DatabaseManager initialized with {db_path}")

    def _create_tables(self):
        """
        Create all tables and indexes defined in the schema.

        This method is called once during initialization.
        It uses IF NOT EXISTS so subsequent calls are safe.
        """
        with self.conn:
            # Execute each CREATE statement in order (foreign keys must exist before references).
            self.conn.execute(CREATE_EXPERIMENTS)
            self.conn.execute(CREATE_HARDWARE_CONFIG)
            self.conn.execute(CREATE_IDLE_BASELINES)
            self.conn.execute(CREATE_RUNS)
            self.conn.executescript(CREATE_RUNS_INDEXES)
            self.conn.execute(CREATE_ORCHESTRATION_EVENTS)
            self.conn.executescript(CREATE_EVENTS_INDEXES)
            self.conn.execute(CREATE_TAX_SUMMARY)
            self.conn.executescript(CREATE_TAX_INDEXES)
            self.conn.executescript(CREATE_ENERGY_SAMPLES)
            self.conn.executescript(CREATE_CPU_SAMPLES)
            self.conn.executescript(CREATE_INTERRUPT_SAMPLES)
            self.conn.execute(CREATE_ML_VIEW)
        logger.debug("All tables and indexes created (if not existed).")

    def _get_hardware_id(self, hardware_info: Dict[str, Any]) -> Optional[int]:
        """
        Retrieve or insert hardware configuration.

        We match on hostname + kernel version because these are stable identifiers
        for a given machine and OS. If a matching record exists, return its hw_id.
        Otherwise, insert a new record and return the new ID.

        Args:
            hardware_info: Dictionary containing hardware fields (hostname, cpu_model, etc.)

        Returns:
            hw_id (int) if hardware_info provided, else None.
        """
        if not hardware_info:
            return None

        # Try to find existing hardware record.
        cursor = self.conn.execute(
            """
            SELECT hw_id FROM hardware_config
            WHERE hostname = ? AND kernel_version = ?
        """,
            (hardware_info.get("hostname"), hardware_info.get("kernel_version")),
        )
        row = cursor.fetchone()
        if row:
            return row["hw_id"]

        # Insert new hardware record.
        cursor = self.conn.execute(
            """
            INSERT INTO hardware_config
            (hostname, cpu_model, cpu_cores, cpu_threads, ram_gb, kernel_version,
             microcode_version, rapl_domains)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
            (
                hardware_info.get("hostname"),
                hardware_info.get("cpu_model"),
                hardware_info.get("cpu_cores"),
                hardware_info.get("cpu_threads"),
                hardware_info.get("ram_gb"),
                hardware_info.get("kernel_version"),
                hardware_info.get("microcode_version"),
                hardware_info.get("rapl_domains"),
            ),
        )
        return cursor.lastrowid

    def _compute_run_state_hash(
        self, run_data: Dict[str, Any], hw_id: Optional[int], baseline_id: Optional[str]
    ) -> str:
        """
        Compute a cryptographic hash of the system state for reproducibility.

        The hash includes:
        - governor
        - turbo_enabled
        - hw_id (which encodes microcode, kernel, etc.)
        - baseline_id

        This allows us to later group runs that had identical system configuration.

        Args:
            run_data: Dictionary containing run fields (from harness output).
            hw_id: hardware_config primary key (or None).
            baseline_id: idle_baselines primary key (or None).

        Returns:
            SHA‑256 hex digest string.
        """
        # Build a canonical string representation of the state.
        state_str = (
            f"{run_data.get('governor', '')}|"
            f"{run_data.get('turbo_enabled', '')}|"
            f"{hw_id}|"
            f"{baseline_id}"
        )
        return hashlib.sha256(state_str.encode()).hexdigest()

    def save_experiment(
        self,
        experiment_meta: Dict[str, Any],
        runs: List[Dict[str, Any]],
        hardware_info: Optional[Dict[str, Any]] = None,
    ) -> int:
        """
        Save a complete experiment with all its runs.

        This is the main entry point for storing results from the harness.
        It performs the following steps:
        1. Insert the experiment metadata.
        2. If hardware_info provided, insert/get hardware_id.
        3. Insert each run (with all metrics, events, samples).
        4. After all runs are inserted, compute tax summaries by pairing
           linear and agentic runs with the same run_number.

        All inserts happen inside a transaction to ensure atomicity.

        Args:
            experiment_meta: Dictionary with keys:
                - name (str): experiment name
                - description (str): optional description
                - workflow_type (str): 'linear' or 'agentic'
                - model_name (str)
                - provider (str)
                - task_name (str)
                - country_code (str, default 'US')
            runs: List of run result dictionaries from the harness.
                  Each run dict must contain:
                  - 'ml_features' (dict with all the 77 fields)
                  - optionally 'layer3_derived'
                  - optionally 'execution'
                  - optionally 'sustainability'
                  - optionally 'orchestration_events'
                  - optionally 'energy_samples', 'cpu_samples', 'interrupt_samples'
            hardware_info: Optional dict with hardware details.

        Returns:
            exp_id of the newly inserted experiment.
        """
        # ---------------------------------------------------------
        # Step 1: Insert experiment record
        # ---------------------------------------------------------
        with self.conn:
            cursor = self.conn.execute(
                """
                INSERT INTO experiments
                (name, description, workflow_type, model_name, provider, task_name, country_code)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
                (
                    experiment_meta.get("name", "unnamed"),
                    experiment_meta.get("description", ""),
                    experiment_meta.get("workflow_type"),
                    experiment_meta.get("model_name"),
                    experiment_meta.get("provider"),
                    experiment_meta.get("task_name"),
                    experiment_meta.get("country_code", "US"),
                ),
            )
            exp_id = cursor.lastrowid

        # ---------------------------------------------------------
        # Step 2: Get or insert hardware configuration
        # ---------------------------------------------------------
        hw_id = self._get_hardware_id(hardware_info) if hardware_info else None

        # ---------------------------------------------------------
        # Step 3: Insert each run
        # ---------------------------------------------------------
        run_ids = {}  # map experiment_id (string) to database run_id
        for run in runs:
            run_id = self._insert_run(exp_id, hw_id, run)
            # The run's ml_features contains an 'experiment_id' field (UUID from harness)
            # We use that to link later for tax summary.
            exp_uuid = run.get("ml_features", {}).get("experiment_id")
            if exp_uuid:
                run_ids[exp_uuid] = run_id

        # ---------------------------------------------------------
        # Step 4: Create tax summaries for paired runs
        # ---------------------------------------------------------
        self._create_tax_summaries(exp_id, run_ids)

        return exp_id

    def _insert_run(
        self, exp_id: int, hw_id: Optional[int], run_data: Dict[str, Any]
    ) -> int:
        """
        Insert a single run into the runs table, plus all associated events/samples.

        This method extracts all necessary fields from the harness output,
        computes derived metrics (energy_per_instruction, thermal_delta, etc.),
        and inserts the main row. Then it inserts orchestration events and
        high‑frequency samples if present.

        Args:
            exp_id: Foreign key to experiments table.
            hw_id: Foreign key to hardware_config (or None).
            run_data: Dictionary containing all data for one run.

        Returns:
            run_id of the newly inserted run.
        """
        # ---------------------------------------------------------
        # Extract data from the nested structure
        # ---------------------------------------------------------
        ml = run_data.get("ml_features", {})  # Flattened ML features (77 columns)
        layer3 = run_data.get("layer3_derived", {})  # DerivedEnergyMeasurement
        exec_data = run_data.get("execution", {})  # Execution metadata
        sus = run_data.get("sustainability", {})  # Sustainability metrics

        # ---------------------------------------------------------
        # Timing: we approximate start/end from harness timestamp and duration.
        # ---------------------------------------------------------
        # harness_timestamp is an ISO string; convert to seconds since epoch.
        harness_ts_str = run_data.get("harness_timestamp", datetime.now().isoformat())
        try:
            dt = datetime.fromisoformat(harness_ts_str)
            start_time_s = dt.timestamp()
        except Exception:
            start_time_s = datetime.now().timestamp()
        start_time_ns = int(start_time_s * 1_000_000_000)

        duration_ms = ml.get("duration_ms", 0)
        duration_ns = int(duration_ms * 1_000_000)
        end_time_ns = start_time_ns + duration_ns

        # ---------------------------------------------------------
        # Energy values: always stored in microjoules.
        # ---------------------------------------------------------
        total_energy_j = ml.get("energy_j", 0)
        total_energy_uj = int(total_energy_j * 1_000_000)

        # For now, dynamic_energy = total_energy (baseline correction later)
        dynamic_energy_uj = total_energy_uj
        baseline_energy_uj = None  # not yet implemented

        avg_power_watts = ml.get("avg_power_watts", 0)

        # ---------------------------------------------------------
        # Performance counters and scheduler
        # ---------------------------------------------------------
        instructions = ml.get("instructions", 0)
        cycles = ml.get("cycles", 0)
        ipc = ml.get("ipc", 0)
        cache_misses = ml.get("cache_misses", 0)
        cache_references = ml.get("cache_references", 0)
        cache_miss_rate = ml.get("cache_miss_rate", 0)
        page_faults = ml.get("page_faults", 0)
        major_page_faults = ml.get("major_page_faults", 0)
        minor_page_faults = ml.get("minor_page_faults", 0)

        context_switches_voluntary = ml.get("context_switches_voluntary", 0)
        context_switches_involuntary = ml.get("context_switches_involuntary", 0)
        total_context_switches = ml.get("total_context_switches", 0)
        thread_migrations = ml.get("thread_migrations", 0)
        run_queue_length = ml.get("run_queue_length", 0)
        kernel_time_ms = ml.get("kernel_time_ms", 0)
        user_time_ms = ml.get("user_time_ms", 0)

        # ---------------------------------------------------------
        # Frequency and ring
        # ---------------------------------------------------------
        frequency_mhz = ml.get("frequency_mhz", 0)
        ring_bus_freq_mhz = ml.get("ring_bus_freq_mhz", 0)

        # ---------------------------------------------------------
        # Thermal metrics
        # ---------------------------------------------------------
        package_temp_celsius = ml.get("package_temp_celsius")
        baseline_temp_celsius = ml.get("baseline_temp_celsius")
        start_temp_c = ml.get("start_temp_c")
        max_temp_c = ml.get("max_temp_c")
        thermal_delta_c = (
            (max_temp_c - start_temp_c)
            if (start_temp_c is not None and max_temp_c is not None)
            else None
        )

        thermal_during_experiment = ml.get("thermal_during_experiment", False)
        thermal_now_active = ml.get("thermal_now_active", False)
        thermal_since_boot = ml.get("thermal_since_boot", False)
        experiment_valid = ml.get("experiment_valid", True)

        # ---------------------------------------------------------
        # C‑states
        # ---------------------------------------------------------
        c2_time_seconds = ml.get("c2_time_seconds", 0)
        c3_time_seconds = ml.get("c3_time_seconds", 0)
        c6_time_seconds = ml.get("c6_time_seconds", 0)
        c7_time_seconds = ml.get("c7_time_seconds", 0)

        # ---------------------------------------------------------
        # MSR / wakeup
        # ---------------------------------------------------------
        wakeup_latency_us = ml.get("wakeup_latency_us", 0)
        interrupt_rate = ml.get("interrupt_rate", 0)
        thermal_throttle_flag = ml.get("thermal_throttle_flag", 0)

        # ---------------------------------------------------------
        # Memory
        # ---------------------------------------------------------
        rss_memory_mb = ml.get("rss_memory_mb", 0)
        vms_memory_mb = ml.get("vms_memory_mb", 0)

        # ---------------------------------------------------------
        # Tokens
        # ---------------------------------------------------------
        total_tokens = ml.get("total_tokens", 0)
        prompt_tokens = ml.get("prompt_tokens", 0)
        completion_tokens = ml.get("completion_tokens", 0)

        # ---------------------------------------------------------
        # Network
        # ---------------------------------------------------------
        dns_latency_ms = ml.get("dns_latency_ms", 0)
        api_latency_ms = ml.get("api_latency_ms", 0)
        compute_time_ms = ml.get("compute_time_ms", 0)

        # ---------------------------------------------------------
        # System state
        # ---------------------------------------------------------
        governor = ml.get("governor", "unknown")
        turbo_enabled = ml.get("turbo_enabled", False)
        is_cold_start = ml.get("is_cold_start", False)
        background_cpu_percent = ml.get("background_cpu_percent", 0)
        process_count = ml.get("process_count", 0)

        # ---------------------------------------------------------
        # Agentic‑specific (may be None for linear runs)
        # ---------------------------------------------------------
        planning_time_ms = ml.get("planning_time_ms")
        execution_time_ms = ml.get("execution_time_ms")
        synthesis_time_ms = ml.get("synthesis_time_ms")
        phase_planning_ratio = ml.get("phase_planning_ratio")
        phase_execution_ratio = ml.get("phase_execution_ratio")
        phase_synthesis_ratio = ml.get("phase_synthesis_ratio")
        llm_calls = ml.get("llm_calls")
        tool_calls = ml.get("tool_calls")
        tools_used = ml.get("tools_used")
        steps = ml.get("steps")
        avg_step_time_ms = ml.get("avg_step_time_ms")
        complexity_level = ml.get("complexity_level")
        complexity_score = ml.get("complexity_score")

        # ---------------------------------------------------------
        # Sustainability
        # ---------------------------------------------------------
        carbon_g = None
        water_ml = None
        methane_mg = None
        if sus:
            carbon_g = sus.get("carbon", {}).get("grams")
            water_ml = sus.get("water", {}).get("milliliters")
            methane_mg = sus.get("methane", {}).get("grams")

        # ---------------------------------------------------------
        # Derived efficiency metrics (computed here)
        # ---------------------------------------------------------
        energy_per_instruction = (
            (total_energy_j / instructions) if instructions else None
        )
        energy_per_cycle = (total_energy_j / cycles) if cycles else None
        energy_per_token = (total_energy_j / total_tokens) if total_tokens else None
        instructions_per_token = (instructions / total_tokens) if total_tokens else None
        interrupts_per_second = interrupt_rate  # already in same units

        # ---------------------------------------------------------
        # Run state hash (cryptographic fingerprint)
        # ---------------------------------------------------------
        baseline_id = run_data.get("baseline_id")  # may be None
        run_state_hash = self._compute_run_state_hash(ml, hw_id, baseline_id)

        # ---------------------------------------------------------
        # Insert the main run record
        # ---------------------------------------------------------
        with self.conn:
            cursor = self.conn.execute(
                """
                INSERT INTO runs (
                    exp_id, hw_id, baseline_id, run_number,
                    start_time_ns, end_time_ns, duration_ns,
                    total_energy_uj, dynamic_energy_uj, baseline_energy_uj, avg_power_watts,
                    instructions, cycles, ipc, cache_misses, cache_references, cache_miss_rate,
                    page_faults, major_page_faults, minor_page_faults,
                    context_switches_voluntary, context_switches_involuntary, total_context_switches,
                    thread_migrations, run_queue_length, kernel_time_ms, user_time_ms,
                    frequency_mhz, ring_bus_freq_mhz,
                    package_temp_celsius, baseline_temp_celsius, start_temp_c, max_temp_c, thermal_delta_c,
                    thermal_during_experiment, thermal_now_active, thermal_since_boot, experiment_valid,
                    c2_time_seconds, c3_time_seconds, c6_time_seconds, c7_time_seconds,
                    wakeup_latency_us, interrupt_rate, thermal_throttle_flag,
                    rss_memory_mb, vms_memory_mb,
                    total_tokens, prompt_tokens, completion_tokens,
                    dns_latency_ms, api_latency_ms, compute_time_ms,
                    governor, turbo_enabled, is_cold_start, background_cpu_percent, process_count,
                    planning_time_ms, execution_time_ms, synthesis_time_ms,
                    phase_planning_ratio, phase_execution_ratio, phase_synthesis_ratio,
                    llm_calls, tool_calls, tools_used, steps, avg_step_time_ms,
                    complexity_level, complexity_score,
                    carbon_g, water_ml, methane_mg,
                    energy_per_instruction, energy_per_cycle, energy_per_token,
                    instructions_per_token, interrupts_per_second,
                    run_state_hash
                ) VALUES (
                    ?, ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?, ?, ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?,
                    ?, ?, ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?, ?,
                    ?, ?,
                    ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?,
                    ?, ?, ?, ?, ?,
                    ?, ?,
                    ?, ?, ?,
                    ?, ?, ?, ?,
                    ?, ?
                )
            """,
                (
                    exp_id,
                    hw_id,
                    baseline_id,
                    ml.get("run_number"),
                    start_time_ns,
                    end_time_ns,
                    duration_ns,
                    total_energy_uj,
                    dynamic_energy_uj,
                    baseline_energy_uj,
                    avg_power_watts,
                    instructions,
                    cycles,
                    ipc,
                    cache_misses,
                    cache_references,
                    cache_miss_rate,
                    page_faults,
                    major_page_faults,
                    minor_page_faults,
                    context_switches_voluntary,
                    context_switches_involuntary,
                    total_context_switches,
                    thread_migrations,
                    run_queue_length,
                    kernel_time_ms,
                    user_time_ms,
                    frequency_mhz,
                    ring_bus_freq_mhz,
                    package_temp_celsius,
                    baseline_temp_celsius,
                    start_temp_c,
                    max_temp_c,
                    thermal_delta_c,
                    thermal_during_experiment,
                    thermal_now_active,
                    thermal_since_boot,
                    experiment_valid,
                    c2_time_seconds,
                    c3_time_seconds,
                    c6_time_seconds,
                    c7_time_seconds,
                    wakeup_latency_us,
                    interrupt_rate,
                    thermal_throttle_flag,
                    rss_memory_mb,
                    vms_memory_mb,
                    total_tokens,
                    prompt_tokens,
                    completion_tokens,
                    dns_latency_ms,
                    api_latency_ms,
                    compute_time_ms,
                    governor,
                    turbo_enabled,
                    is_cold_start,
                    background_cpu_percent,
                    process_count,
                    planning_time_ms,
                    execution_time_ms,
                    synthesis_time_ms,
                    phase_planning_ratio,
                    phase_execution_ratio,
                    phase_synthesis_ratio,
                    llm_calls,
                    tool_calls,
                    tools_used,
                    steps,
                    avg_step_time_ms,
                    complexity_level,
                    complexity_score,
                    carbon_g,
                    water_ml,
                    methane_mg,
                    energy_per_instruction,
                    energy_per_cycle,
                    energy_per_token,
                    instructions_per_token,
                    interrupts_per_second,
                    run_state_hash,
                ),
            )
            run_id = cursor.lastrowid

        # ---------------------------------------------------------
        # Insert orchestration events (if any)
        # ---------------------------------------------------------
        if "orchestration_events" in run_data:
            self._insert_orchestration_events(run_id, run_data["orchestration_events"])

        # ---------------------------------------------------------
        # Insert high‑frequency samples (if any)
        # ---------------------------------------------------------
        if "energy_samples" in run_data:
            self._insert_energy_samples(run_id, run_data["energy_samples"])
        if "cpu_samples" in run_data:
            self._insert_cpu_samples(run_id, run_data["cpu_samples"])
        if "interrupt_samples" in run_data:
            self._insert_interrupt_samples(run_id, run_data["interrupt_samples"])

        return run_id

    def _insert_orchestration_events(self, run_id: int, events: List[Dict[str, Any]]):
        """
        Insert a list of orchestration events for a given run.

        Each event is expected to contain:
            step_index (int), phase (str), event_type (str),
            start_time_ns (int), end_time_ns (int), duration_ns (int),
            power_watts (float), cpu_util_percent (float), interrupt_rate (float),
            event_energy_uj (int), tax_contribution_uj (int), tax_percent (float).

        Args:
            run_id: Foreign key to runs table.
            events: List of event dictionaries.
        """
        with self.conn:
            for ev in events:
                self.conn.execute(
                    """
                    INSERT INTO orchestration_events
                    (run_id, step_index, phase, event_type, start_time_ns, end_time_ns,
                     duration_ns, power_watts, cpu_util_percent, interrupt_rate,
                     event_energy_uj, tax_contribution_uj, tax_percent)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                    (
                        run_id,
                        ev.get("step_index"),
                        ev.get("phase"),
                        ev.get("event_type"),
                        ev.get("start_time_ns"),
                        ev.get("end_time_ns"),
                        ev.get("duration_ns"),
                        ev.get("power_watts"),
                        ev.get("cpu_util_percent"),
                        ev.get("interrupt_rate"),
                        ev.get("event_energy_uj"),
                        ev.get("tax_contribution_uj"),
                        ev.get("tax_percent"),
                    ),
                )

    def _insert_energy_samples(self, run_id: int, samples: List[Dict[str, Any]]):
        """
        Insert high‑frequency RAPL samples.

        Each sample must contain:
            timestamp_ns (int), and at least one of pkg_energy_uj, core_energy_uj,
            uncore_energy_uj, dram_energy_uj.

        Args:
            run_id: Foreign key to runs table.
            samples: List of sample dictionaries.
        """
        with self.conn:
            for s in samples:
                self.conn.execute(
                    """
                    INSERT INTO energy_samples
                    (run_id, timestamp_ns, pkg_energy_uj, core_energy_uj, uncore_energy_uj, dram_energy_uj)
                    VALUES (?, ?, ?, ?, ?, ?)
                """,
                    (
                        run_id,
                        s.get("timestamp_ns"),
                        s.get("pkg_energy_uj"),
                        s.get("core_energy_uj"),
                        s.get("uncore_energy_uj"),
                        s.get("dram_energy_uj"),
                    ),
                )

    def _insert_cpu_samples(self, run_id: int, samples: List[Dict[str, Any]]):
        """
        Insert CPU samples (utilization and frequency).

        Each sample must contain:
            timestamp_ns (int), cpu_util_percent (float), cpu_freq_mhz (float).

        Args:
            run_id: Foreign key to runs table.
            samples: List of sample dictionaries.
        """
        with self.conn:
            for s in samples:
                self.conn.execute(
                    """
                    INSERT INTO cpu_samples
                    (run_id, timestamp_ns, cpu_util_percent, cpu_freq_mhz)
                    VALUES (?, ?, ?, ?)
                """,
                    (
                        run_id,
                        s.get("timestamp_ns"),
                        s.get("cpu_util_percent"),
                        s.get("cpu_freq_mhz"),
                    ),
                )

    def _insert_interrupt_samples(self, run_id: int, samples: List[Dict[str, Any]]):
        """
        Insert interrupt rate samples.

        Each sample must contain:
            timestamp_ns (int), interrupts_per_sec (float).

        Args:
            run_id: Foreign key to runs table.
            samples: List of sample dictionaries.
        """
        with self.conn:
            for s in samples:
                self.conn.execute(
                    """
                    INSERT INTO interrupt_samples
                    (run_id, timestamp_ns, interrupts_per_sec)
                    VALUES (?, ?, ?)
                """,
                    (run_id, s.get("timestamp_ns"), s.get("interrupts_per_sec")),
                )

    def _create_tax_summaries(self, exp_id: int, run_ids: Dict[str, int]):
        """
        Create tax summary entries for all agentic runs in this experiment.

        We assume that linear and agentic runs are paired by having the same
        run_number within the experiment. For each such pair, we compute:
            tax_uj = agentic_dynamic_uj - linear_dynamic_uj
            tax_percent = (tax_uj / agentic_dynamic_uj) * 100

        The result is stored in orchestration_tax_summary.

        Args:
            exp_id: Experiment ID.
            run_ids: Mapping from harness experiment UUID to database run_id.
                     Not actually used here because we query directly.
        """
        # ---------------------------------------------------------
        # Get all runs for this experiment with their run_number and workflow_type
        # ---------------------------------------------------------
        cursor = self.conn.execute(
            """
            SELECT r.run_id, r.run_number, e.workflow_type
            FROM runs r
            JOIN experiments e ON r.exp_id = e.exp_id
            WHERE r.exp_id = ?
        """,
            (exp_id,),
        )
        runs_info = cursor.fetchall()

        # ---------------------------------------------------------
        # Build a mapping: run_number -> {linear: run_id, agentic: run_id}
        # ---------------------------------------------------------
        pairs = {}
        for r in runs_info:
            num = r["run_number"]
            if num not in pairs:
                pairs[num] = {}
            pairs[num][r["workflow_type"]] = r["run_id"]

        # ---------------------------------------------------------
        # For each pair that has both linear and agentic, compute tax
        # ---------------------------------------------------------
        for num, pair in pairs.items():
            linear_id = pair.get("linear")
            agentic_id = pair.get("agentic")
            if linear_id and agentic_id:
                # Retrieve dynamic energies
                cursor = self.conn.execute(
                    """
                    SELECT dynamic_energy_uj FROM runs WHERE run_id IN (?, ?)
                """,
                    (linear_id, agentic_id),
                )
                energies = {
                    row["run_id"]: row["dynamic_energy_uj"] for row in cursor.fetchall()
                }
                linear_uj = energies.get(linear_id, 0)
                agentic_uj = energies.get(agentic_id, 0)
                tax_uj = agentic_uj - linear_uj
                tax_percent = (tax_uj / agentic_uj * 100) if agentic_uj > 0 else 0

                with self.conn:
                    self.conn.execute(
                        """
                        INSERT INTO orchestration_tax_summary
                        (linear_run_id, agentic_run_id, linear_dynamic_uj, agentic_dynamic_uj,
                         orchestration_tax_uj, tax_percent)
                        VALUES (?, ?, ?, ?, ?, ?)
                    """,
                        (
                            linear_id,
                            agentic_id,
                            linear_uj,
                            agentic_uj,
                            tax_uj,
                            tax_percent,
                        ),
                    )

    # --------------------------------------------------------------------------
    # QUERY METHODS
    # --------------------------------------------------------------------------

    def get_run(self, run_id: int) -> Optional[Dict[str, Any]]:
        """
        Retrieve a single run by its primary key.

        Args:
            run_id: Database run_id.

        Returns:
            Dictionary with all run columns, or None if not found.
        """
        cursor = self.conn.execute("SELECT * FROM runs WHERE run_id = ?", (run_id,))
        row = cursor.fetchone()
        return dict(row) if row else None

    def get_runs_by_experiment(self, exp_id: int) -> List[Dict[str, Any]]:
        """
        Retrieve all runs belonging to an experiment, ordered by run_number.

        Args:
            exp_id: Experiment ID.

        Returns:
            List of run dictionaries.
        """
        cursor = self.conn.execute(
            "SELECT * FROM runs WHERE exp_id = ? ORDER BY run_number", (exp_id,)
        )
        return [dict(row) for row in cursor.fetchall()]

    def get_tax_summaries(self, exp_id: Optional[int] = None) -> List[Dict[str, Any]]:
        """
        Retrieve tax summary entries, optionally filtered by experiment.

        Args:
            exp_id: If provided, only summaries for runs in that experiment.

        Returns:
            List of tax summary dictionaries.
        """
        if exp_id is None:
            cursor = self.conn.execute("SELECT * FROM orchestration_tax_summary")
        else:
            # Join with runs to filter by experiment
            cursor = self.conn.execute(
                """
                SELECT ots.* FROM orchestration_tax_summary ots
                JOIN runs r ON ots.linear_run_id = r.run_id
                WHERE r.exp_id = ?
            """,
                (exp_id,),
            )
        return [dict(row) for row in cursor.fetchall()]

    def get_ml_data(self, workflow: Optional[str] = None) -> List[Dict[str, Any]]:
        """
        Retrieve flattened ML data from the ml_features view.

        This is the primary method for loading data into ML pipelines.
        The view already contains all features and targets in a single row per run.

        Args:
            workflow: If provided, filter by workflow_type ('linear' or 'agentic').

        Returns:
            List of dictionaries, each representing one run with all ML columns.
        """
        if workflow:
            cursor = self.conn.execute(
                "SELECT * FROM ml_features WHERE workflow_type = ?", (workflow,)
            )
        else:
            cursor = self.conn.execute("SELECT * FROM ml_features")
        return [dict(row) for row in cursor.fetchall()]

    def close(self):
        """
        Close the database connection.
        """
        self.conn.close()

    # --------------------------------------------------------------------------
    # Context manager support
    # --------------------------------------------------------------------------
    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


"""stand alone test"""

if __name__ == "__main__":
    """
    Standalone test for DatabaseManager.
    Creates an in‑memory database, inserts a dummy experiment and run,
    and queries back the data to verify functionality.
    """
    import os
    import tempfile

    print("=" * 60)
    print("Testing DatabaseManager standalone...")
    print("=" * 60)

    # Use a temporary file for testing
    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as tmp:
        db_path = tmp.name

    try:
        # Initialize database (creates tables)
        db = DatabaseManager(db_path)

        # Dummy experiment metadata
        experiment_meta = {
            "name": "test_experiment",
            "description": "Standalone test",
            "workflow_type": "linear",
            "model_name": "test-model",
            "provider": "test",
            "task_name": "test-task",
            "country_code": "US",
        }

        # Dummy run data (minimal ml_features)
        dummy_run = {
            "ml_features": {
                "run_number": 1,
                "duration_ms": 1000.0,
                "energy_j": 0.5,
                "avg_power_watts": 0.5,
                "instructions": 1000000,
                "cycles": 2000000,
                "ipc": 0.5,
                "cache_misses": 10000,
                "cache_references": 100000,
                "cache_miss_rate": 0.1,
                "page_faults": 10,
                "major_page_faults": 0,
                "minor_page_faults": 10,
                "context_switches_voluntary": 50,
                "context_switches_involuntary": 5,
                "total_context_switches": 55,
                "thread_migrations": 10,
                "run_queue_length": 0.1,
                "kernel_time_ms": 10.0,
                "user_time_ms": 20.0,
                "frequency_mhz": 2000.0,
                "ring_bus_freq_mhz": 1800.0,
                "package_temp_celsius": 45.0,
                "baseline_temp_celsius": 40.0,
                "start_temp_c": 42.0,
                "max_temp_c": 46.0,
                "thermal_during_experiment": False,
                "thermal_now_active": False,
                "thermal_since_boot": False,
                "experiment_valid": True,
                "c2_time_seconds": 0.1,
                "c3_time_seconds": 0.2,
                "c6_time_seconds": 0.0,
                "c7_time_seconds": 0.0,
                "wakeup_latency_us": 5.0,
                "interrupt_rate": 1000.0,
                "thermal_throttle_flag": 0,
                "rss_memory_mb": 150.0,
                "vms_memory_mb": 750.0,
                "total_tokens": 100,
                "prompt_tokens": 40,
                "completion_tokens": 60,
                "dns_latency_ms": 10.0,
                "api_latency_ms": 50.0,
                "compute_time_ms": 40.0,
                "governor": "powersave",
                "turbo_enabled": True,
                "is_cold_start": True,
                "background_cpu_percent": 2.5,
                "process_count": 350,
                "planning_time_ms": None,
                "execution_time_ms": None,
                "synthesis_time_ms": None,
                "phase_planning_ratio": None,
                "phase_execution_ratio": None,
                "phase_synthesis_ratio": None,
                "llm_calls": None,
                "tool_calls": None,
                "tools_used": None,
                "steps": None,
                "avg_step_time_ms": None,
                "complexity_level": None,
                "complexity_score": None,
                "experiment_id": "dummy-uuid-1234",
            },
            "sustainability": {
                "carbon": {"grams": 0.0001},
                "water": {"milliliters": 0.001},
                "methane": {"grams": 0.00001},
            },
        }

        # Save experiment
        exp_id = db.save_experiment(experiment_meta, [dummy_run], hardware_info=None)
        print(f"✅ Experiment saved with ID: {exp_id}")

        # Retrieve runs
        runs = db.get_runs_by_experiment(exp_id)
        print(f"✅ Retrieved {len(runs)} run(s)")

        # Check ML view
        ml_data = db.get_ml_data()
        print(f"✅ ML view has {len(ml_data)} row(s)")

        # Print first run's energy
        if runs:
            print(f"   Run energy: {runs[0]['total_energy_uj'] / 1e6:.4f} J")

        db.close()
        print("\n✅ All tests passed!")

    except Exception as e:
        print(f"\n❌ Test failed: {e}")
        import traceback

        traceback.print_exc()
    finally:
        # Clean up temp file
        os.unlink(db_path)
